services:
  traefik:
    hostname: traefik
    container_name: traefik
    image: traefik:v3
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - "TZ"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${VOLUMES_DIR}/traefik/acme:/etc/traefik/acme
      - ${VOLUMES_DIR}/traefik/log:/var/log
      - ./conf/traefik-dynamic.yml:/etc/traefik/config/dnamic.yml
      - ./conf/traefik-static.dev.yml:/etc/traefik/traefik.yml
      - ./cert:/etc/traefik/certs
      - "/etc/timezone:/etc/timezone:ro"
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik-dashboard.entrypoints=websecure
      - traefik.http.routers.traefik-dashboard.service=api@internal
      - traefik.http.routers.traefik-dashboard.rule=Host(`traefik.${DOMAINNAME}`)

  whoami:
    image: traefik/whoami
    restart: unless-stopped
    container_name: whoami
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.entrypoints=websecure
      - traefik.http.routers.whoami.rule=Host(`whoami.${DOMAINNAME}`)

networks:
  traefik:
    name: traefik
    ipam:
      config:
        - subnet: ${TRAEFIK_SUBNET}
