version: "3.5"
services:
  traefik:
    hostname: traefik
    image: traefik:2.6
    container_name: traefik
    # restart: always
    security_opt:
      - no-new-privileges:true
    environment:
      - "TZ"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${VOLUMES_DIR}/acme:/etc/traefik/acme
      - ${VOLUMES_DIR}/log:/var/log
      - ./conf/traefik-dynamic.yml:/etc/traefik/config/dnamic.yml
      - ./conf/traefik-static.dev.yml:/etc/traefik/traefik.yml
      - ./cert:/etc/traefik/certs
      - "/etc/timezone:/etc/timezone:ro"
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik-dashboard.entrypoints=websecure
      - traefik.http.routers.traefik-dashboard.service=api@internal
      - traefik.http.routers.traefik-dashboard.rule=Host(`traefik.docker.localhost`)

  whoami:
    image: containous/whoami
    # restart: always
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.entrypoints=websecure
      - traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)

  smtp4dev:
    image: rnwood/smtp4dev:v3
    hostname: "smtp"
    volumes:
      # This is where smtp4dev stores the database..
      - ${VOLUMES_DIR}/smtp4dev:/smtp4dev
    ports:
      - "25:25"
      - "143:143"
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.smtp4dev.entrypoints=websecure
      - traefik.http.routers.smtp4dev.rule=Host(`smtp.docker.localhost`)
      - traefik.http.routers.smtp4dev.service=smtp4dev
      - traefik.http.services.smtp4dev.loadbalancer.server.port=80

      - traefik.tcp.routers.smtp4dev_imap.entrypoints=imap
      - traefik.tcp.routers.smtp4dev_imap.rule=HostSNI(`smtp.docker.localhost`)
      - traefik.tcp.routers.smtp4dev_imap.service=smtp4dev_imap
      - traefik.tcp.routers.smtp4dev_imap.tls
      - traefik.tcp.services.smtp4dev_imap.loadbalancer.server.port=143

      - traefik.tcp.routers.smtp4dev_smtp.entrypoints=smtp
      - traefik.tcp.routers.smtp4dev_smtp.rule=HostSNI(`smtp.docker.localhost`)
      - traefik.tcp.routers.smtp4dev_smtp.service=smtp4dev_smtp
      - traefik.tcp.routers.smtp4dev_smtp.tls
      - traefik.tcp.services.smtp4dev_smtp.loadbalancer.server.port=25

    environment:
      - ServerOptions__HostName=smtp4dev
      - RelayOptions__SmtpPort=25
      - ServerOptions__ImapPort=143
      #- ServerOptions__NumberOfMessagesToKeep=100
      #- ServerOptions__NumberOfSessionsToKeep=100
      #- ServerOptions__TlsMode=None
      #- ServerOptions__TlsCertificate=
      #- RelayOptions__SmtpServer=
      #- RelayOptions__AllowedEmailsString=
      #- RelayOptions__SenderAddress=
      #- RelayOptions__Login=
      #- RelayOptions__Password=

networks:
  traefik:
    name: traefik
    ipam:
      config:
        - subnet: ${TRAEFIK_SUBNET}
