log:
  level: INFO

accessLog:
  filePath: "/var/log/accesslog.json"
  format: json
  fields:
    defaultMode: keep
    headers:
      names:
        x-forwarded-for: keep

  filters:
    statusCodes:
      # - "200-299"
      - "400-499"
      - "500-599"

api:
  dashboard: true

providers:
  file:
    directory: /etc/traefik/config
    watch: true
  docker:
    exposedByDefault: false
    network: traefik

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "websecure"
          scheme: https
          permanent: true
  websecure:
    address: ":443"
    http:
      middlewares:
        - devheaders@file
      tls: true
  smtp:
    address: ":25"
  imap:
    address: ":143"
  internal:
    address: ":8080"
