log:
  level: INFO

accessLog:
  filters:
    retryAttempts: true
    minDuration: "10ms"
    statusCodes:
      - "400-499"
      - "500-599"
api:
  dashboard: true

providers:
  file:
    directory: /etc/traefik/config
    watch: true
  docker:
    exposedByDefault: false
    network: traefik

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "websecure"
          scheme: https
          permanent: true
  websecure:
    address: ":443"
    http:
      middlewares:
        - devheaders@file
      tls: true
  smtp:
    address: ":25"
  imap:
    address: ":143"
  internal:
    address: ":8080"
